version: '3.8'

services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ecommerce_backend
    volumes:
      - .:/app
    depends_on:
      - mongo_db
    ports:
      - '8000:8000'

  mongo_db:
    image: mongo
    container_name: ecommerce_database
    volumes:
      - ecommerce_data:/data/db/
    logging:
      driver: none

volumes:
  ecommerce_data: {}
